#+title: Detailed installation guidance for GeGeDe

* Quick start

Any "standard" method to install Python packages should work (let me know if
otherwise).  Installing with =uv= is recommended and assumed here.

First, need not install GeGeDe to use it:

#+begin_example
uvx gegede
#+end_example

To make have it in your =~/.local/bin/=:

#+begin_example
uv tool install gegede
gegede
#+end_example

Installing a pre-releases:

#+begin_example
uv tool install git+https://github.com/brettviren/gegede
#+end_example

Additional details follow.

* Installation of GeGeDe

The core functionality of GeGeDe is requires pure Python or common binary
packages.  Additional functionality is available in environments that provide additional binaries.  See below for some guidance on how to install them.

GeGeDe itself may be installed in "the usual Python ways" and some examples are
given below.

** User installation

See quick start for basic, initial installation.

To upgrade to a new version:

#+begin_example
uv tool upgrade gegede
#+end_example

Or to uninstall
#+begin_example
uv tool uninstall gegede
#+end_example

** Developer installation

This also uses =uv=.  Other methods are possible for the interested developer.

#+begin_example
git clone git@github.com:brettviren/gegede.git  # or use your fork
cd gegede
uv sync
uv run gegede
#+end_example

For running tests

#+begin_example
uv sync --extra test
uv run pytest
#+end_example

See [[file:releases.org]] for how releases are made.


* Binary dependencies

By default, GeGeDe relies on a set of pure-Python dependencies and has support for  optional dependencies.

 - GDML :: requires [[http://lxml.de/][lxml]] for emitting XML for GDML
 - ROOT :: (optional) for ROOT-based tests and direct ROOT export, PyROOT is needed
 - pivy :: (optional) for experimental FreeCAD support, pivy/coin3d is needed.

** For GDML export

#+BEGIN_EXAMPLE
  $ sudo apt-get install libxml2 libxslt1-dev
#+END_EXAMPLE

** For ROOT export

Installing GeGeDe with optional ROOT support will allow export directly to ROOT
formats.  Note, ROOT is not required to export GDML, which later ROOT may
ingest.

ROOT provides its own PyROOT interface.  As of end of 2025, there seems to be no
easy way to install GeGeDe in "usual Python ways" so that it can depend on ROOT.  What I do find:

- PyROOT on PyPI is wholly unrelated to ROOT.  When I say "PyROOT" here, I do
  not mean this package.

- rootpy has last commit 7 years ago and any case requires PyROOT to already be
  installed.

- ROOT on PyPI does provide ROOT but does not include TGeoManager.

Building ROOT from source or otherwise relying on being available is then the
last resort.  The details to that are left to the user but some hints.

#+begin_example
$ PYTHONPATH=$HOME/opt/root/lib LD_LIBRARY_PATH=$HOME/opt/root/lib python -c 'import ROOT; print(ROOT.TGeoManager)'
<class cppyy.gbl.TGeoManager at 0x18fd1c90>
#+end_example

Note, PyROOT is, apparently, sensitive to exact matching of the Python version
used to build it and to run it.

GeGeDe will fail semi-gracefully if ROOT features are requested in an
environment that lacks ROOT.

** For Pivy/Coin3D/FreeCAD

This is experimental and left as an exercise for the interested.


