#+title: Detailed installation guidance for GeGeDe

* Dependencies

GeGeDe relies on a set of pure-Python dependencies but for maximal usage some optional dependencies must be provided that require compilation.  

 - GDML :: requires [[http://lxml.de/][lxml]] for emitting XML for GDML
 - ROOT :: (optional) for ROOT-based tests and direct ROOT export, PyROOT is needed
 - pivy :: (optional) for experimental FreeCAD support, pivy/coin3d is needed.

** For GDML export

#+BEGIN_EXAMPLE
  $ sudo apt-get install libxml2 libxslt1-dev
#+END_EXAMPLE

** For ROOT export

ROOT is not required to use GeGeDe.  It is only needed to let GeGeDe directly
export to ROOT formats.  Without direct ROOT support one may still generate GDML
output with GeGeDe and then transport the GDML output to a different environment
that provides ROOT.

ROOT can be installed and if its PyROOT is available in the user environment it
will be used.  Or, it can be installed via the "ROOT" package on PyPI.  See user and developer installation sections below.

** For Pivy/Coin3D/FreeCAD

This is experimental and left as an exercise for the interested.

* Installation of GeGeDe

GeGeDe is pure Python.  It effectively supports only Python 3 due to
its dependencies dropping support for dead Python 2 (RIP).  GeGeDe may
be installed in "the usual Python ways" and some examples are given
below.

** Using uv

Using =uv= is highly recommended.

*** User installation

#+begin_example
uv tool install git+https://github.com/brettviren/gegede
#+end_example

To include ROOT

#+begin_example
uv tool install --with ROOT git+https://github.com/brettviren/gegede
#+end_example

Later upgrade:

#+begin_example
uv tool upgrade gegede
#+end_example

Or, later uninstall
#+begin_example
uv tool uninstall gegede
#+end_example

*** Developer installation

This also uses =uv=.  Other ways are possible for the interested developer.

#+begin_example
git clone git@github.com:brettviren/gegede.git  # or use your fork
cd gegede
uv sync
uv run gegede
#+end_example

For running tests

#+begin_example
uv sync --extra test
uv run pytest
#+end_example

If ROOT (PyROOT) will be used then you must let ~direnv~ know how to
include it by appending this to its configuration file:

#+begin_example
uv sync --extra root
uv run python -c 'import ROOT; print (ROOT.__version__)'
6.37.01
#+end_example

Kitchen sink

#+begin_example
uv sync --all-extras
#+end_example

