* Prerequisites

** For ROOT export

See the ROOT home page for how to install ROOT:
https://root.cern.ch/

ROOT 6 is recommended.  Once installed and after entering your Python
environment (see below) you can test if PyROOT is available:

#+BEGIN_EXAMPLE
  $ python --version
  (make sure it is Python 3.x)
  $ python -c 'import ROOT'
  (make sure no errors)
#+END_EXAMPLE

To use ROOT you may need to add/set its library directory to ~PYTHONPATH~.

** For GDML export

#+BEGIN_EXAMPLE
  $ sudo apt-get install libxml2 libxslt1-dev
#+END_EXAMPLE


* Installation of GeGeDe

GeGeDe is pure Python with a few dependencies.  It supports Python 3.  Python 2.x will likely not work.  GeGeDe and dependencies may be installed in "the usual way".

** Virtualenv

The easiest way to install GeGeDe for yourself is via a "virtual environment".  

#+BEGIN_EXAMPLE
  $ python3 -m venv ggdvenv
  $ source ggdvenv/bin/activate
#+END_EXAMPLE

At this point, any Python packages you install go into your virtual environment (called "=ggdvenv=" here).

** Installing GeGeDe

Get the GeGeDe source and install like:

#+BEGIN_EXAMPLE
  $ git clone https://github.com/brettviren/gegede.git
  $ cd gegede/
  $ python setup.py install
#+END_EXAMPLE

* Development

To set up for building and testing GGD "in source":

#+BEGIN_EXAMPLE
  $ python3 -m venv ggdvenvdev
  $ source ggdvenvdev/bin/activate
  $ python setup.py develop
#+END_EXAMPLE

The tests are meant to be run via [[https://nose.readthedocs.org][nose]]:

#+BEGIN_EXAMPLE
  $ pip install nose
  $ nosetests
  ....................
  ----------------------------------------------------------------------
  Ran 20 tests in 1.657s

  OK
#+END_EXAMPLE

Tests should be run from the source directory in a virtual environment prepared with "setup.py develop".  All tests should pass if all dependencies are installed.  If ROOT or other dependencies are not installed, tests which need them will naturally fail.  These should be marked clearly with an error message like:

#+BEGIN_EXAMPLE
ERROR: Failure: ModuleNotFoundError (No module named 'ROOT')
#+END_EXAMPLE

Note, you may still use GeGeDe without ROOT installed in the virtual
environment, eg by making GDML files and using them from another
environment.
